# Generated by Django 4.0.5 on 2022-07-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=255)),
                ('movie_artist', models.CharField(max_length=255)),
                ('movie_data', models.CharField(max_length=6)),
                ('movie_views', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=255)),
                ('song_artist', models.CharField(max_length=255)),
                ('song_data', models.CharField(max_length=6)),
                ('song_views', models.IntegerField(default=0)),
            ],
        ),
    ]
